#!/usr/bin/bash

e="$1"

echo """#!/usr/bin/bash

set -euo pipefail

user_config=\"\${XDG_CONFIG_HOME:-\$HOME/.config}/$e\"
prefix_conf=\"\${user_config}/prefix.conf\"
flags_file=\"\${user_config}/flags.conf\"

echo \"若出现无法获取的情况 请关闭启动器中类似「映射游戏文件夹的功能」 并保证游戏于 Z 盘下运行\"
echo \"别问 问就是很简陋 为了最小化补丁 绝对不是嫌麻烦不想大改\"
echo \"原 userData 文件夹 移动至 \${user_config}/userData\"

if [[ -f \"\${prefix_conf}\" ]]; then
    WINEPREFIX=\"\$(cat \"\${prefix_conf}\")\"
    export WINEPREFIX
else
    mkdir -p $\"\${user_config}/userData\"
    echo \"你可能需要前往 \${prefix_conf} 设置你的 WINEPREFIX\"
    echo \"\\\$ echo -n '/path/to/wineprefix' > '\${prefix_conf}'\"
    echo \"虽然我也不知道为什么要这么干 但这个项目偏偏就是干了\"
    exit 1
fi

if [[ -f \"\${flags_file}\" ]]; then
    mapfile -t < \"\${flags_file}\" CODEMAPFILE
fi

appflags=()
for line in \"\${CODEMAPFILE[@]}\"; do
    if [[ ! \"\${line}\" =~ ^[[:space:]]*#.* ]] && [[ -n \"\${line}\" ]]; then
        appflags+=(\"\${line}\")
    fi
done

/usr/bin/electron \"/usr/lib/warp-exports/$e/app\" \"\${appflags[@]}\"  \"\$@\"
""" > "$2"
