#!/usr/bin/bash
#shellcheck disable=SC2034

# 要安装的包
packages=(
    millennium
)

repos=(
)

prepare_packages=(
)

fake_depend=(
    aseprite # for `aseprite-universal-pixel-theme-zh-hans`
    steam # for `millennium`
)

prepare_map=(
)
