#!/usr/bin/bash
#shellcheck disable=SC2034

# 要安装的包
packages=(
    linuxqq-nt-bwrap
)

repos=(
)

prepare_packages=(
)

fake_depend=(
    aseprite=1.3.14.4 # for `aseprite-universal-pixel-theme-zh-hans`
    kwin # for `kwin-plugins-moyingji-git`
)

prepare_map=(
)
