name: Build

permissions:
    contents: write

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Run docker
            uses: addnab/docker-run-action@v3
            with:
                image: archlinux:base-devel
                shell: bash
                options: |
                    -v ${{ github.workspace }}:/work
                    -w /work
                run: |
                    source ./BuildAUR/Entrypoint

          - name: Update packages
            uses: ncipollo/release-action@v1
            with:
                allowUpdates: true
                removeArtifacts: true
                tag: "packages"
                artifacts: "./pkgs/*.pkg.tar.zst"
                token: ${{ secrets.GITHUB_TOKEN }}
